pycupiddb/__init__.py,sha256=EQpFeSHb1knGN0C2czsxxKOlWY5-WK70s7sNkuG_y3w,115
pycupiddb/client.py,sha256=kJae_QY_fKQQ_T05EQYLYFuMFcqJsKiGpa6cVFomiKk,1864
pycupiddb/commands.py,sha256=PCJLsPMTemMiOF8AxdSpwdjAH7dJ5yETi9U0F2XzwXQ,6295
pycupiddb/connection.py,sha256=vfxfpaf0XbxVwrW34yhECPwre5EREzpoIiYw64gpZlA,7068
pycupiddb/exceptions.py,sha256=1F3ql_gKtErPi2Y4MuFX_wBHrXW3M7aGLpS0crrln4I,178
pycupiddb-1.0.0.dist-info/LICENSE,sha256=1kJ9gvSe9DiFz_optTigubArvLORRTooqAzC3ZMyp8E,11342
pycupiddb-1.0.0.dist-info/METADATA,sha256=Hy0rD4CZDB6Tojv9P6pYVt5-55c0m1oh-SPgreNt5sg,14499
pycupiddb-1.0.0.dist-info/WHEEL,sha256=UvcQYKBHoFqaQd6LKyqHw9fxEolWLQnlzP0h_LgJAfI,91
pycupiddb-1.0.0.dist-info/top_level.txt,sha256=s7gc5nOoMjF7jBcWhh8miKs7Nth1w6cUFymDsiTZ0Bk,10
pycupiddb-1.0.0.dist-info/RECORD,,
